project3_mail/mail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailview.urls')),
    path('user/', include('user.urls')),
]

project3_mail/user/urls.py
from django.urls import path
from . import views
app_name= 'user'
urlpatterns= [
    path('', views.index, name='index'),
    path('login', views.loginView, name='login'),
    path('logout', views.logoutView, name='logout'),
    path('register', views.register, name='register'),  
    path('changingpasswd', views.changingpasswd, name='changingPasswd'),
    path('deleteacc', views.deleteAcc, name='deleteAcc'),
]

project3_mail/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    def __str__(self):
        return f"{self.email}"

project3_mail/user/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import User
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.urls import reverse
# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return render(request, 'user/index.html')
    else:
        return HttpResponseRedirect(reverse('user:login'))

def loginView(request):
    if request.method=="POST":
        email= request.POST["mail"]
        passwd= request.POST["passwd"]
        user = authenticate(request, username=email, password=passwd)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('mailview:index'))
        else:
            return render(request, 'user/login.html', {
                'message': 'Invalid Email or/and Password'
            })
        
    else:
        return render(request, 'user/login.html')


def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('user:login'))

def register(request):
    if request.method=='POST':
        email= request.POST["mail"]
        passwd= request.POST["passwd"]
        confim= request.POST["confirm"]
        if passwd!=confim:
            return render(request, 'user/register.html',{
                'err': 'Password and Confirmation must match!',
            })
        try:
            user= User.objects.create_user(
                username= email,
                email= email,
                password= passwd
            )
            user.save()
        except IntegrityError as e:
            return render(request, 'user/register.html',{
                'err': "Email address already taken!",
            })
        return render(request, 'user/login.html')
    else:
        return render(request, 'user/register.html')

def changingpasswd(request):
    if request.method=="POST":
        email= request.POST["mail"]
        oldpasswd= request.POST["oldpasswd"]
        newpasswd= request.POST["newpasswd"]
        confirm= request.POST["confirm"]
        if newpasswd!= confirm:
            return render(request, 'user/changingpasswd.html',{
                'message': 'New Password and Confirmation must match!'
            })
        user= authenticate(request, username= email, password= oldpasswd)
        if user is not None:
            user.set_password(newpasswd)
            user.save()
            return render(request, 'user/changingpasswd.html', {
                'message': 'Password was update'
            })
        else:
            return render(request, 'user/changingpasswd.html',{
                'message': 'Email or/and Password is not Found!'
            })
    else:
        return render(request, 'user/changingpasswd.html')

def deleteAcc(request):
    if request.method=="POST":
        email= request.POST["mail"]
        passwd= request.POST["passwd"]
        confirm= request.POST["confirm"]
        if passwd!=confirm:
            return render(request, 'user/deleteacc.html',{
                'message': "Password & confirmation must match!"
            })
        user= authenticate(request, username= email, password= passwd)

        if user is not None:
            user.delete()
            return render(request, 'user/login.html', {
                'message': 'Delete user successful!'
            })

        else:
            return render(request, 'user/deleteacc.html',{
                'message': "Email or/and Password not exist!"
            })
    else:
        return render(request, 'user/deleteacc.html')

project3_mail/user/templates/user/changingpasswd.html
{% extends 'user/layout.html' %}
{% block title %}
Changing Password
{% endblock %}

{% block body %}
<h4 class="text-danger">{{message}}</h4>
<h1 class="header">Changing Password: </h1>
<div class="container">
    <div class="row">
        <div class="col">
            <form action="{% url 'user:changingPasswd' %}" method="post">
                {% csrf_token %}

                <label for="mail">Email: </label>
                <input type="email" class="form-control margin-inp-changing mt-1" name="mail" id="mail"
                    placeholder="Enter email">
                <div class="mt-3 ">
                    <label for="oldpasswd">Password: </label>
                    <input type="password" class="form-control margin-inp-changing mt-1" name="oldpasswd" id="oldpasswd"
                        placeholder="Enter password">
                </div>
                <div class="mt-3 ">
                    <label for="newpasswd">New Password: </label>
                    <input type="password" class="form-control margin-inp-changing mt-1" name="newpasswd" id="newpasswd"
                        placeholder="Enter new password">
                </div>
                <div class="mt-3 mb-3">
                    <label for="confirm">Confirmation New Password: </label>
                    <input type="password" class="form-control margin-inp-changing mt-1" name="confirm" id="confirm"
                        placeholder="Enter confirmation">
                    <input type="submit" class="btn btn-primary margin-inp-changing mt-2" value="Changing">
                </div>
            </form>
        </div>
    </div>
    <a href="{% url 'user:index' %}" class="">Back To User</a>
</div>
{% endblock %}

project3_mail/user/templates/user/deleteacc.html
{% extends 'user/layout.html' %}

{% block title %}
Delete Account
{% endblock %}

{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        document.querySelector('form').onsubmit = function (event) {
            let choice = confirm("Do you really want to Delete Current Account?")
            if (choice === false) {
                event.preventDefault();
            }
        }
    })
</script>
{% endblock %}

{% block body %}
<div class="container">
    <h4 class="text-danger">{{message}}</h4>
    <h1 class="header mt-3">Delete Account: </h1>
    <form action="{% url 'user:deleteAcc' %}" method="post">
        {% csrf_token %}
        <label for="mail">Email: </label>
        <input type="email" class="form-control margin-inp-changing mb-3 mt-1" name="mail" id="mail"
            placeholder="Enter email">
        <label for="passwd">Password: </label>
        <input type="password" class="form-control margin-inp-changing mb-3 mt-1" name="passwd" id="oldpasswd"
            placeholder="Enter password">
        <label for="confirm">Confirmation Password: </label>
        <input type="password" class="form-control margin-inp-changing mb-3 mt-1" name="confirm" id="confirm"
            placeholder="Enter confirmation">
        <input type="submit" id="submit" class="btn btn-primary margin-inp-changing mb-3 mt-1" value="Delete">
    </form>
    <a href="{% url 'user:index' %}" class="">Back To User</a>
</div>
{% endblock %} mt-1

project3_mail/user/templates/user/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

project3_mail/user/templates/user/login.html
{% extends 'user/layout.html' %}

{% block title %}
Login
{% endblock %}

{% block body %}
<h3 class="text-danger mt-3 mb-3"> {{message}} </h3>
<h1 class="mt-4 ms-4">Login Form: </h1>
<div class="container">
    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <div class="mt-3 mb-3">
            <label for="mail" class="mb-1">Email: </label>
            <input type="email" name="mail" id="mail" placeholder="Enter email" class="form-control">
        </div>

        <div class="mb-3">
            <label for="passwd" class="mb-1">Password: </label>
            <input type="password" name="passwd" id="passwd" placeholder="Enter password" class="form-control">
        </div>

        <div>
            <input type="submit" class="btn btn-primary" value="Login">
        </div>
    </form>
</div>
<p class="ms-3 mt-3">Do not have an account? <a href="{% url 'user:register' %}">Register Here!</a></p>
{% endblock %}

project3_mail/user/templates/user/register.html
{% extends "user/layout.html" %}

{% block title %}
Register
{% endblock %}

{% block js %}

{% endblock %}

{% block body %}
<h3 class="mb-4 mt-3 ms-2 text-danger">{{err}}</h3>
<h1 class="ms-4 mt-4">Register Form: </h1>
<div class="container">
    <form action="{% url 'user:register' %}" class="validation" method="post">
        {% csrf_token %}
        <div class="mt-3 mb-3">
            <label for="mail" class="mb-1">Email: </label>
            <input type="email" class="form-control" name="mail" id="mail" placeholder="Enter Email">
        </div>

        <div class="mb-3">
            <label for="password" class="mb-1">Password: </label>
            <input type="password" class="form-control" name="passwd" id="password" placeholder="Enter Password">
        </div>

        <div class="mb-3">
            <label for="confirm" class="mb-1">Confimation: </label>
            <input type="password" class="form-control" name="confirm" id="confirm" placeholder="Enter Confimation">
        </div>

        <div class="mb-3">
            <input type="submit" class="btn btn-primary" value="Register">
        </div>
    </form>
</div>
<p class="ms-3 mt-3">Already have an account? <a href="{% url 'user:login' %}">Login Here!</a></p>
{% endblock %}