project2_commerce/Commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("auctions.urls")),
    path('users/', include("users.urls"))
]

project2_commerce/auctions/urls.py
from django.urls import path
from . import views

app_name= "auctions"
urlpatterns= [
    path('',views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:listing_id>/', views.listing, name="listing"),
    path('categories/', views.categories, name="categories"),
    path('watchlist/', views.watchlist, name="watchlist"),
    path('<int:listing_id>/bid', views.place_bid, name="place_bid"),
    path('<int:listing_id>/comments', views.comment, name="comment"),
    path('<int:listing_id>/close', views.close, name="close")
]

project2_commerce/users/urls.py
from django.urls import path
from . import views

app_name= "users"
urlpatterns= [
    path('', views.index, name="index"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register, name="register"),
    path('changing/', views.changing, name="changing")
]

project2_commerce/auctions/models.py
from django.db import models
from users.models import User

# Create your models here.
class Category(models.Model):
    name= models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"

class Listing(models.Model):
    title= models.CharField(unique=True, max_length=64)
    decription= models.CharField(max_length=512)
    time= models.DateTimeField(auto_now=True)
    watchlist= models.ManyToManyField(User, blank=True, related_name="watchlist")
    create_user= models.ForeignKey(User, on_delete=models.CASCADE, related_name="createlist")
    category= models.ForeignKey(Category, on_delete= models.CASCADE, related_name="listcategory")
    winner= models.ForeignKey(User, null=True ,on_delete=models.CASCADE, related_name="wasbid", blank=True)
    currentbid= models.FloatField()
    imgurls= models.URLField(blank=True)
    is_active= models.BooleanField(default=True)

class Bid(models.Model):
    bidder= models.ForeignKey(User, on_delete=models.CASCADE, related_name="bidders")
    bid= models.FloatField()
    time= models.DateTimeField(auto_now=True)
    listing= models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bidlist")

    def __str__(self):
        return f"{self.bidder.username}: {self.listing.title}"

class Comment(models.Model):
    author= models.ForeignKey(User, on_delete=models.CASCADE, related_name="authors")
    content= models.CharField(max_length=512)
    time= models.DateTimeField(auto_now=True)
    listing= models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comment")

project2_commerce/auctions/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from .models import Listing, Bid, Category, Comment
# Create your views here.
def index(request):
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.all().filter(is_active= True)
    })

def create(request):
    if request.method=="POST":
        type= request.POST["category"]
        category= Category.objects.get(name=type)
        try:
            Listing.objects.create(
                title= request.POST["title"],
                decription= request.POST["decription"], 
                create_user= request.user,
                category= category,
                currentbid= float(request.POST["startingbid"]),
                imgurls= request.POST["img_url"]
            )
        except Exception:
            return render(request, "auctions/create.html",{
                'message': "Please Check Against Listing Information"
            })
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        if request.user.is_authenticated:
            return render(request, "auctions/create.html")
        else:
            return HttpResponseRedirect(reverse("users:index"))
        
def listing(request, listing_id):
    _listing= Listing.objects.get(pk=listing_id)

    #To Check if this listing is a previous listing or not
    if request.session.get("listing", listing_id)!=listing_id:
        del request.session["display_num"]
        request.session["listing"]= listing_id
    if "listing" not in request.session:
        request.session["listing"]= listing_id

    #session of bid
    if "bid_massage" not in request.session:
        request.session["bid_massage"]=''
        bid_massage= ''
    else:
        bid_massage= request.session["bid_massage"]
        del request.session["bid_massage"]
    #create session of comment
    if "display_num" not in request.session:
        request.session["display_num"]= 4
    if not request.session.get(f"comment_{listing_id}"):
        #Get all comment id of 1 listing to session
        request.session[f"comment_{listing_id}"]= [cmt.id for cmt in _listing.comment.all()]
        
    
    #Get list id and list objects of comment need display
    lst_cmt_id= request.session[f"comment_{listing_id}"][None:request.session["display_num"]]
    display_cmt= [Comment.objects.get(pk=id) for id in lst_cmt_id]
    del lst_cmt_id

    
    #Bid announces
    list_bid= _listing.bidlist.all()
    _case= 2
    try:
        if list_bid.get(bid=_listing.currentbid).bidder==request.user:
            _case=1
    except ObjectDoesNotExist:
        pass
    if not request.user.is_authenticated or not list_bid.filter(bidder= request.user).exists():
        _case=0

    #check watchlist   
    in_watchlist= _listing.watchlist.all().filter(id= request.user.id).exists()

    if _listing.is_active:
        return render(request, "auctions/listing.html", {
            'listing': _listing,
            'num_of_bid':  _listing.bidlist.count(),
            'case': _case,
            'in_watchlist': in_watchlist,
            'bid_massage': bid_massage,
            'comments': display_cmt
        })
    else:
        return render(request, "auctions/close.html", {
            'listing': _listing,
            'in_watchlist': in_watchlist,
            'bid_massage': bid_massage,
            'comments': display_cmt,
            'winner': _listing.winner
        })

def categories(request):
    if request.method=="POST":
        _type= request.POST["type"]
        list_item= Category.objects.get(name=_type).listcategory.all().filter(is_active= True)

        if not list_item:
            return render(request, "auctions/category.html", {
            "announce": "Not Have Listing In This Category"
        })
        return render(request, "auctions/category.html", {
            "categorylist": list_item
        })
        
    else:
        category= Category.objects.all()
        return render(request, "auctions/categories.html", {
            'categories': category
        })
    
def watchlist(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:index"))
    if "list_listing" not in request.session:
        request.session["list_listing"]= [listing.id for listing in request.user.watchlist.all()]
    if request.session["list_listing"]!= len(request.user.watchlist.all()):
        request.session["list_listing"]= [listing.id for listing in request.user.watchlist.all()]
    if request.method=="POST":
        listing_id= int(request.POST["listing_id"])
        if not listing_id in request.session["list_listing"]:
            Listing.objects.get(pk=listing_id).watchlist.add(request.user)
            request.session["list_listing"].append(listing_id)
            request.session.modified= True
        else:
            Listing.objects.get(pk=listing_id).watchlist.remove(request.user)
            request.session["list_listing"].remove(listing_id)
            request.session.modified = True
        return HttpResponseRedirect(reverse("auctions:listing", args=[listing_id,]))
    else:
        listings= [Listing.objects.get(id=index) for index in request.session["list_listing"]]
        return render(request, "auctions/watchlist.html", {
            "listings": listings
        })

def place_bid(request, listing_id):
    if request.method=="POST" and request.user.is_authenticated:
        bid= float(request.POST["bid"])
        _listing = Listing.objects.get(pk=listing_id)
        if bid > _listing.currentbid:
            _listing= Listing.objects.get(pk=listing_id)
            _listing.currentbid= bid
            _listing.save()

            _bid= Bid.objects.create(
                bidder= request.user,
                bid= bid,
                listing= Listing.objects.get(pk=listing_id)
            )
            _bid.save()

            # exists session sovling
            if "bid_massage" in request.session:
                del request.session["bid_massage"]
            return HttpResponseRedirect(reverse("auctions:listing", args=[listing_id,]))
        else:
            request.session["bid_massage"]= 'The bid must have more than current bid'
            return HttpResponseRedirect(reverse("auctions:listing", args=[listing_id,]))
    else:
        return HttpResponseRedirect(reverse("users:index"))

def comment(request, listing_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:index"))
    if request.method=="POST":
        _listing= Listing.objects.get(pk=listing_id)
        if request.POST.get("submit","")=="Comment":
            cmt= Comment.objects.create(
                author= request.user,
                content= request.POST["content"],
                listing= _listing
            )
            cmt.save()
            request.session["display_num"]+=1
            #Insert in to beginning of session
            request.session[f"comment_{listing_id}"]= [cmt.id,] + request.session[f"comment_{listing_id}"]
            return HttpResponseRedirect(reverse("auctions:listing", args=[listing_id,]))
        if request.POST["more_cmt"]=="Display More Comments":
            request.session["display_num"]+=5
            return HttpResponseRedirect(reverse("auctions:listing", args=[listing_id,]))
        
def close(request, listing_id):
    if request.method=="POST":
        _listing= Listing.objects.get(pk=listing_id)
        _listing.is_active= False
        if _listing.bidlist.all().filter(bid= _listing.currentbid).exists():
            _listing.winner= _listing.bidlist.all().get(bid= _listing.currentbid).bidder
        _listing.save()
        return HttpResponseRedirect(reverse("auctions:listing", args=[listing_id,]))

        
        
        

project2_commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %}
    <title>Categories</title>
{% endblock %}

{% block body %}
    <form action="{% url 'auctions:categories' %}" method="post">
        {% csrf_token %}
        <div class="group-btcate">
            {% for cate in categories %}
            <input type="submit" name="type" value="{{cate.name}}" class="btcate">
            {% endfor %}
        </div>
    </form>
{% endblock %}

project2_commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block title %}
<title>Category</title>
{% endblock %}

{% block body %}
    {% if announce %}
    <h2>{{announce}}</h2>
    {% endif %}
    {% for item in categorylist %}
    <div class="listing-info">
    <div  class="lst-img">
    <img src="{{item.imgurls}}" alt="Not Images For This Product">
    </div>
    <div class="lst-text-info">
        <h4>Title: <span>{{item.title}}</span></p></h4>
        <h4>Price: <span>{{item.currentbid}}$</span></h4>
        <h4>Decription: <span>{{item.decription}}</span></h4>
        <h4>Time: <span>{{item.time}}</span></h4>
        <a href="{% url 'auctions:listing' item.id %}">View By Listing</a>
    </div>
    </div>
    {% endfor %}
{% endblock %}

project2_commerce/auctions/templates/auctions/close.html
{% extends "auctions/listing_layout.html" %}

{% block bid %}
<div class="close">
    {% if request.user == winner %}
        <h2>You Won</h2>
    {% else %}
        <h2>The Winner Is: {{winner.last_name}}</h2>
    {% endif %}
</div>
{% endblock %}

project2_commerce/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block title %}
    <title>Create Listing</title>
{% endblock %}

{% block body %}
<h1>Create Listing: </h1>
<style>
    .base-attr{
        height: 40vh;
        width: 40vw;
        display: flex;
        justify-content: space-between;
    }
    .inp{
        height: 4vh;
        width: 15vw;
    }
</style>
    <h3>{{message}}</h3>
    <form action="{% url 'auctions:create' %}" method="post">
    {% csrf_token %}
<div class="base-attr">
    <div>
        <p>Title: </p>
        <input type="text" name="title" class="inp">
        <p>Starting Bid: </p>
        <input type="text" name="startingbid" class="inp">
        <p>Image Urls: </p>
        <input type="url" name="img_url" id="img-url" class="inp">
    </div>
    <div>
        <p>Select Category: </p>
        <select name="category" style="height: 5vh">
            <option value="Book">Book</option>
            <option value="Course">Course</option>
            <option value="Ticket">Ticket</option>
            <option value="Electronic Deivce">Electronic Deivce</option>
            <option value="Jewelry">Jewelry</option>
            <option value="Mechanical Equipment">Mechanical Equipment</option>
            <option value="Utilities">Utilities</option>
            <option value="Sports">Sports</option>
            <option value="Shoes">Shoes</option>
            <option value="Decorations">Decorations</option>
            <option value="Houseware">Houseware</option>
            <option value="Clothes">Clothes</option>
        </select>
    </div>
</div>
    <div>
        <p>Decription: </p>
        <textarea name="decription" cols="50vw" rows="6"></textarea>
    </div>
        <input type="submit" value="Create Listing" style="padding: 7px 17px; margin-top: 10px;">
        <div style="margin-bottom: 10vh;"></div>
    </form>

{% endblock %}

project2_commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% block title %}
<title>Auctions</title>
{% endblock %}

{% block body %} 
    {% for item in listings %}
    <div class="listing-info">
    <div  class="lst-img">
    <img src="{{item.imgurls}}" alt="Not Images For This Product">
    </div>
    <div class="lst-text-info">
        <h4>Title: <span>{{item.title}}</span></p></h4>
        <h4>Price: <span>{{item.currentbid}}$</span></h4>
        <h4>Decription: <span>{{item.decription}}</span></h4>
        <h4>Time: <span>{{item.time}}</span></h4>
        <a href="{% url 'auctions:listing' item.id %}">View By Listing</a>
    </div>
    </div>
    {% endfor %}
{% endblock %}

project2_commerce/auctions/templates/auctions/listing.html
{% extends "auctions/listing_layout.html" %}

{% block bid %}
<div class="bid-active">
    <h2 style="margin-left: 8vw;">{{listing.currentbid}}$</h2>
    <div class="announce">
        <p style="margin-right: 3px; margin-top: -10px;">{{num_of_bid}} bids so far.</p>
        {% if case == 1 %}
        <p style="margin-top: -10px; color: rgb(7, 91, 91);">Your bid is the current bid</p>
        {% elif case == 2 %}
        <p style="margin-top: -10px; color: red;">Your bid was pressed down</p>
        {% endif %}
    </div>


    <form action="{% url 'auctions:place_bid' listing.id %}" method="post">
        {% csrf_token %}
        <div class="bid-place">
        <input type="number" step="0.01" name="bid" style="width: 21vw; padding: 10px 0;margin-bottom: 10px;">
        <input type="submit" value="Place Bid" style="width: 10vw; padding: 6px 0; margin: 0 0 10px 4.7vw; background-color: rgb(160, 235, 226);">
        </div>
</form>

<div class="announce" style="color: red;">
    {{bid_massage}}
</div>
</div>
{% endblock %}

{% block comment %}
<div class="comment">
    <form action="{% url 'auctions:comment' listing.id %}" method="post">
        {% csrf_token %}
        <textarea autofocus="false" name="content" cols="100vw" rows="5"
            placeholder="Pleases Write Your Comments"></textarea>
        <br>
        <input type="submit" value="Comment" name="submit" style="padding: 8px; background-color: rgb(127, 215, 253);">
    </form>
</div>
{% endblock %}

project2_commerce/auctions/templates/auctions/listing_layout.html
{% extends "auctions/layout.html" %}

{% block title %}
<title>Listing</title>
{% endblock %}

{% block body %}
<div class="head">
    <h1 style="color: rgb(94, 63, 206);">Listing: {{listing.title}}</h1>
    <form action="{% url 'auctions:close' listing.id %}" method="post">
        {% csrf_token %}
        {% if listing.create_user == request.user and listing.is_active == True %}
        <input type="submit" value="Close" style="padding: 10px 20px; background-color: rgb(238, 152, 152);">
        {% endif %}
    </form>
</div>

<div>
    <form action="{% url 'auctions:watchlist' %}" method="post">
        {% csrf_token %}
        {% if in_watchlist %}
        <button value="{{listing.id}}" name="listing_id" class="btwatch-remove">Remove WatchList</button>
        {% else %}
        <button value="{{listing.id}}" name="listing_id" class="btwatch-add">Add WatchList</button>
        {% endif %}
    </form>
</div>

<div class="img-decription">
    <div class="img">
        <img src="{{listing.imgurls}}" alt="">
    </div>
    <h3 style="color: rgb(109, 116, 7);">DECRIPTIONS: <p style="color: black; font-weight: normal;">
            {{listing.decription}}</p>
    </h3>

</div>

{% block bid %}
{% endblock %}

{% block comment %}
{% endblock %}
<div class="comment-display">

    {% for cmt in comments %}
    <div class="cmt">
        <p>{{cmt.content}}</p>
        <p style="margin-top: -10px;">~By: {{cmt.author.username}}</p>
    </div>
    {% endfor %}

    <form action="{% url 'auctions:comment' listing.id %}" method="post">
        {% csrf_token %}
        <div>
            <input type="submit" name="more_cmt" value="Display More Comments"
                style="padding: 10px 5px; background-color: rgb(186, 214, 214);">
        </div>
    </form>

    <div class="detail">
        <h2>Details</h2>
        <ul>
            <li>List By: {{listing.usercreate.last_name}}</li>
            <li>Category: {{listing.category.name}}</li>
            <li>Time List: {{listing.time}}</li>
        </ul>
    </div>
</div>
{% endblock %}

project2_commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}
{% block title %}
<title>WatchList</title>
{% endblock %}

{% block body %} 
    {% for item in listings %}
    <div class="listing-info">
    <div  class="lst-img">
    <img src="{{item.imgurls}}" alt="Not Images For This Product">
    </div>
    <div class="lst-text-info">
        <h4>Title: <span>{{item.title}}</span></p></h4>
        <h4>Price: <span>{{item.currentbid}}$</span></h4>
        <h4>Decription: <span>{{item.decription}}</span></h4>
        <h4>Time: <span>{{item.time}}</span></h4>
        <a href="{% url 'auctions:listing' item.id %}">View By Listing</a>
    </div>
    </div>
    {% endfor %}
{% endblock %}