project3_mail/mail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailview.urls')),
    path('user/', include('user.urls')),
]

project3_mail/mailview/urls.py
from django.urls import path
from . import views

app_name= "mailview"
urlpatterns= [
    path('', views.index, name='index'),
    path('home/<str:mail_box>', views.locateMailBox, name='locateMailBox'),
    path('mail/<int:mail_id>', views.detail, name='detail'),
    path('paging/', views.paging, name='paging'),
    #API Routes
    path('emails', views.compose, name='compose'),
    path('emails/<int:mail_id>', views.mail_detail, name='emailDetail'),
    path('emails/<str:mail_box>', views.mailbox, name='mailbox')
]

project3_mail/user/urls.py
from django.urls import path
from . import views
app_name= 'user'
urlpatterns= [
    path('', views.index, name='index'),
    path('login', views.loginView, name='login'),
    path('logout', views.logoutView, name='logout'),
    path('register', views.register, name='register'),  
    path('changingpasswd', views.changingpasswd, name='changingPasswd'),
    path('deleteacc', views.deleteAcc, name='deleteAcc'),
]

project3_mail/mailview/models.py
from typing import Any
from django.db import models
from user.models import User
# Create your models here.
class Email(models.Model):
    user= models.ForeignKey(User, on_delete=models.PROTECT, related_name='owner', null= True)
    sender= models.ForeignKey(User, on_delete=models.CASCADE, related_name='your_mail', null= True)
    recipients= models.ManyToManyField(User, related_name='receive_mail', blank=True)
    subject= models.CharField(max_length=128)
    body= models.TextField()
    timestamp= models.DateTimeField(auto_now_add=True)
    read= models.BooleanField(default= False)
    archived= models.BooleanField(default= False)

    def __str__(self):
        return f"Mail of {self.user}"
    
    def serialize(self):
        recipients= self.recipients.all()
        emails= []
        for recipient in recipients:
            emails.append(recipient.email)
        return {
            'id': self.pk,
            'user': self.user.email,
            'sender': self.sender.email,
            'recipients': emails,
            'subject': self.subject,
            'body': self.body,
            'timestamp': self.timestamp.strftime("%B %d %Y, %H:%M %p"),
            'read': self.read,
            'archived': self.archived
        }
    

project3_mail/mailview/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
import json
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import Email, User
import time

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return render(request, 'mailview/index.html')
    else:
        return HttpResponseRedirect(reverse('user:login'))

@login_required
@csrf_exempt
def compose(request):
    if request.method!="POST":
        return JsonResponse({'message': 'Require post request!'}, status=400)
    data= json.loads(request.body)
    recipients= data.get('recipients','')
    emails= [email.strip() for email in recipients.split(',')]
    if emails==[]:
        return JsonResponse({'message' : 'At least one recipients'}, status=400)
    recipients= []
    for email in emails:
        try:
            user= User.objects.get(email=email)
            recipients.append(user)
        except User.DoesNotExist:
            return JsonResponse({'message' : 'Recipients does not exist!'}, status=400)
    subject= data.get('subject','')
    body= data.get('body','')

    users= set()
    users.add(request.user)
    users.update(recipients)
    for user in users:
        email= Email(
            user= user,
            sender= request.user,
            subject= subject,
            body= body,
            read= request.user == user
        )
        email.save()
        for recipient in recipients:
            email.recipients.add(recipient)
        email.save()
    return JsonResponse({'message' : 'Successful to Post'}, status=201)

@login_required
def mailbox(request,mail_box):
    if mail_box=='inbox':
        emails= Email.objects.filter(
            user= request.user, 
            recipients= request.user,
            archived= False
        )
    elif mail_box=='sent':
        emails= Email.objects.filter(
            user= request.user,
            sender= request.user
        )
    elif mail_box=='archived':
        emails= Email.objects.filter(
            user= request.user,
            recipients= request.user,
            archived= True
        )
    else:
        return JsonResponse({'message' : 'Invalid Get Request'}, status=400)
    
    emails= emails.order_by('-timestamp').all()
    return JsonResponse([email.serialize() for email in emails], safe=False)

@login_required
@csrf_exempt
def mail_detail(request, mail_id):
    try:
        email= Email.objects.get(id=mail_id, user= request.user)
    except Email.DoesNotExist:
        return JsonResponse({'message' : 'Id not exists!'}, status=400)
    
    
    if request.method=="PUT":
        data= json.loads(request.body)
        if data.get('read'):
            email.read= data.get('read')
        if data.get('archived','')!='':
            email.archived= data.get('archived')
        email.save()
    
    return JsonResponse(email.serialize(), status=200)


@login_required
def detail(request, mail_id):
    return render(request, 'mailview/index.html', {
        "isURL": True,
        "id": mail_id
    })

@login_required
def locateMailBox(request, mail_box):
    return render(request, 'mailview/index.html', {
        "isURL": True,
        "box": mail_box
    })

def paging(request):
        return render(request, 'mailview/paging.html')

project3_mail/mailview/templates/mailview/index.html
{% extends 'mailview/layout.html' %}
{% load static %}
{% block title %}
MailBox
{% endblock %}

{% block body %}
<div class="container">
    {% if isURL %}
    {% if id %}
    <script>
        detail_getAndHandleAPI("{{id}}");
    </script>
    {% else %}
    <script>
        if ("{{box}}" !== 'compose')
            document.addEventListener('DOMContentLoaded', () => loadMailBox("{{box}}"));
        else
            document.addEventListener('DOMContentLoaded', () => loadCompose());
    </script>
    {% endif %}
    {% endif %}
    <div id="detailview" style="display: none;"></div>

    <div id="mailBox" style="display: none;"></div>

    <div id="compose">
        <h1 class="mt-1 text-success">Compose: </h1>
        <form id="compose-form">
            <div class="input-group mb-3 row">
                <span class="input-group-text col-sm-2">Sender: </span>
                <input class="form-control" readonly type="text" name="" id="sender" value="{{request.user.email}}">
            </div>

            <div class="input-group mb-3 row">
                <span class="input-group-text col-sm-2">Recipients: </span>
                <input type="text" class="form-control " name="" id="recipients" placeholder="Enter recipients List">
            </div>

            <div class="input-group mb-3 row">
                <span class="input-group-text col-sm-2">Subject: </span>
                <input type="text" class="form-control" name="" id="subject" placeholder="Enter subject">
            </div>

            <div class="mb-3 row">
                <span class="input-group-text col-sm-2">Body: </span>
                <textarea name="" class="form-control mt-3 col-12" id="body" cols="30" rows="6"></textarea>
            </div>

            <button id="bt-oldmail" class="btn mb-2" style="display: none;">...</button>

            <div class="mb-3 row" style="display: none;" id="oldmail-block">
                <span class="input-group-text col-sm-2">Old Mail: </span>
                <textarea name="" class="form-control mt-3 col-12" id="oldmail" cols="30" rows="6"></textarea>
            </div>

            <div class="d-flex justify-content-end mb-3">
                <input id="submit-compose" type="submit" class="btn btn-outline-primary" value="Sent">
            </div>

        </form>
    </div>
</div>

{% if not isURL %}
<script>
    loadMailBox('Inbox');
</script>
{% endif %}
</div>
{% endblock %}


{% block script %}
<script src="{% static 'mailview/inbox.js' %}"></script>
<script src="{% static 'mailview/paging.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

project3_mail/mailview/templates/mailview/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'mailview/mailstyle.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'mailview/userstyle.css' %}">
 
    <title>{% block title %}{% endblock %}</title>
    {% block script %}
    {% endblock %}
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <nav class="navbar fixed-top w-25 pt-0"
                    style="padding: 0; margin-bottom: 1000px; overflow-y: auto; background-color: rgb(240, 240, 239);">
                    <div class="container-fluid nav2 d-flex flex-column justify-content-start" style="padding: 0;">
                        <ul class="navbar-nav w-100">
                            <li class="nav-item pt-2 pb-2 w-75" style="margin-left: 7%;">
                                <a href="{% url 'mailview:index' %}">
                                    <img src="{% static 'mailview/logo_gmail_lockup_default_2x_r5.png' %}" alt=""
                                        class="w-75">
                                </a>
                                <h5 class="a ms-2"><a href="{% url 'user:index' %}" class="text-info">{{request.user.email}}</a></h5>
                            </li>
                            <li class="nav-item pills pt-3">
                                <button class="nav-link" id="Inbox">
                                    <h5>Inbox</h5>
                                </button>
                            </li>
                            <li class="nav-item pills pt-3">
                                <button class="nav-link" id="Compose">
                                    <h5>Compose</h5>
                                </button>
                            </li>
                            <li class="nav-item pills pt-3">
                                <button class="nav-link" id="Sent">
                                    <h5>Sent</h5>
                                </button>
                            </li>
                            <li class="nav-item pills pt-3">
                                <button class="nav-link" id="Archived">
                                    <h5>Archived</h5>
                                </button>
                            </li>
                            <li class="nav-item pills pt-3">
                                <h5><a class="nav-link" href="{% url 'user:logout' %}">Logout</a></h5>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="col-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

project3_mail/mailview/templates/mailview/paging.html
{% extends 'mailview/layout.html' %}
{% load static %}
{% block title %}
MailBox
{% endblock %}

{% block body %}
<div>
    <div id="email"></div>
    <ul class="pagination"></ul>
</div>
{% endblock %}


{% block script %}
<script src="{% static 'mailview/paging.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}