Project1_wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name= 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("serch/",views.serch, name="serch"),
    path("create/", views.create, name="create"),
    path("random/", views.random_page, name="random_page"),
    path("<str:name>/", views.greed, name="greed"),
    path("edit/<str:entry>/", views.edit, name="edit")
]

Project1_wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("encyclopedia.urls"))
]

Project1_wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from random import choice
from . import util
from django import forms

class CreateTextareaForm(forms.Form):
    my_title= forms.CharField(
        widget= forms.TextInput(attrs={
            'style':'width: 70vw',
            'placeholder': 'Enter Title'
        }),
        label=""
    )
    my_textarea= forms.CharField(
        widget=forms.Textarea(attrs={
            'style': 'margin-top: 20px; width: 70vw; height: 60vh',
            'placeholder': 'Enter MarkDown Content'
        }),
        label=""
    )

class EditTextareaForm(forms.Form):
    textarea_edit= forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={'style': 'width: 60vw; height: 60vh'}
        ), 
        
    )

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def greed(request, name):
    for entry in util.list_entries():
        if name.lower() == entry.lower():
            html_content= util.convertToHTML(entry)
            return render(request, "encyclopedia/greed.html",{
                "util": html_content,
                "title": name
            })
    return render(request, "encyclopedia/greed.html")

def serch(request):
    serch_result_page= []
    if request.method=="POST":
        serch_text= str(request.POST['q'])
        entries= util.list_entries()
        
        for entry in entries:
            if serch_text.lower()==entry.lower():
                return HttpResponseRedirect(reverse("encyclopedia:greed", args=[entry]))
            elif serch_text.lower() in entry.lower():
                serch_result_page.append(entry)
        return render(request, "encyclopedia/serch_result_page.html",{
            "entries": serch_result_page
        })
    else:
        return render(request, "encyclopedia/serch_result_page.html",{
            "entries": serch_result_page
        })
            
def create(request):
    check=False
    if request.method=="POST":
        form= CreateTextareaForm(request.POST)
        if form.is_valid():
            title_data= form.cleaned_data["my_title"]
            textarea_data= form.cleaned_data["my_textarea"]
            for entry in util.list_entries():
                if title_data.lower() == entry.lower():
                    return render(request, "encyclopedia/create.html",{
                        "form": form,
                        "check": True
                    })
            util.save_entry(title_data, textarea_data)
            return HttpResponseRedirect(reverse("encyclopedia:greed", args=[entry]))
        else:
            return render(request, "encyclopedia/create.html",{
                "form": form,
                "check": False
            })
    else:
        return render(request, "encyclopedia/create.html",{
                "form": CreateTextareaForm(),
                "check": False
            })

def edit(request, entry):
    if request.method=="POST":
        form= EditTextareaForm(request.POST)
        if form.is_valid():
            edit_content= form.cleaned_data["textarea_edit"]
            util.save_entry(entry,edit_content)
            return HttpResponseRedirect(reverse("encyclopedia:greed", args=[entry,]))
        else:
            return render(request, "encyclopedia/edit.html",{
                "form": form,
                "entry": entry
            })
    else:
        return render(request, "encyclopedia/edit.html",{
            "form": EditTextareaForm(
                initial={'textarea_edit': util.get_entry(entry)}
            ),
            "entry": entry
        })
     
def random_page(request):
    entries= util.list_entries()
    random_entry= choice(entries)
    return HttpResponseRedirect(reverse("encyclopedia:greed", args=[random_entry]))
        

Project1_wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    Create Page
{% endblock %}
{% block custom_css %}
<style>
.save{
    position: absolute;
    left: 10px;
    bottom: 50px;
    border: 1px solid black;
    border-radius: 3px;
}

.save:hover{
    background-color: rgb(210, 208, 208);
}
</style>
{% endblock %}
{% block body %}
    <h1>Create Page</h1>
    {% if check %}
        <p>Errors, Title is duplicated</p>
    {% endif %}
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Save" class="save">
    </form>
{% endblock %}

Project1_wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}
{% block custom_css %}
<style>
.save{
    position: absolute;
    left: 10px;
    bottom: 18vh;
    border: 1px solid black;
    border-radius: 3px;
}

.save:hover{
    background-color: rgb(210, 208, 208);
}
</style>
{% endblock %}
{% block body %}
    <h1>Edit Page</h1>
    <form action="{% url 'encyclopedia:edit' entry %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Save Edits" class="save">
    </form>
{% endblock %}

Project1_wiki/encyclopedia/templates/encyclopedia/greed.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block custom_css %}
<style>
    .solid{
        width: 100vw;
        border: 1px rgb(198, 198, 198) solid;
        position: relative;
        right: 10px;
    }
    .edit{
        width: 25px;
        height: 20px;
        background-color: rgb(63, 223, 223);
        padding: 10px;
        border: 1px black solid;
        border-radius: 4px;
        text-decoration: none;
        color: black;
        position: relative;
        top: 40px;
    }

    .edit:hover{
        background-color: rgb(133, 206, 206);;
    }
</style>
{% endblock %}

{% block body %}
    {% if util %}
        {{util|safe}}
    {% else %}
        <h1>Page Was Not Found!</h1>
    {% endif %}
    <p class="solid"></p>
    <a href="{% url 'encyclopedia:edit' title %}" class="edit">Edit</a>

{% endblock %}

Project1_wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

Project1_wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        {% block custom_css %}{% endblock %}
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="post" action="{% url 'encyclopedia:serch' %}">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Project1_wiki/encyclopedia/templates/encyclopedia/serch_result_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Serch Result Page
{% endblock %}

{% block body %}
    <h1>Serch Result Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:greed' entry %}">{{entry}}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}